PART_ONE = "A"
PART_TWO = "B"

DAY_TAG = "<DAY>"

INPUT_FILE_TEMPLATE = "i_day_<DAY>.txt"
INPUT_SAMPLE_FILE_TEMPLATE = "i_day_<DAY>_sample.txt"
OUTPUT_A_FILE_TEMPLATE = "o_day_<DAY>_a.txt"
OUTPUT_B_FILE_TEMPLATE = "o_day_<DAY>_b.txt"
OUTPUT_SAMPLE_FILE_TEMPLATE = "o_day_<DAY>_sample.txt"

INPUT_TYPE = "I"
INPUT_SAMPLE_TYPE = "IS"
OUTPUT_A_TYPE = "OA"
OUTPUT_B_TYPE = "OB"
OUTPUT_SAMPLE_TYPE = "OS"

FILE_TEMPLATES = {
    INPUT_TYPE: INPUT_FILE_TEMPLATE,
    INPUT_SAMPLE_TYPE: INPUT_SAMPLE_FILE_TEMPLATE,
    OUTPUT_A_TYPE: OUTPUT_A_FILE_TEMPLATE,
    OUTPUT_B_TYPE: OUTPUT_B_FILE_TEMPLATE,
    OUTPUT_SAMPLE_TYPE: OUTPUT_SAMPLE_FILE_TEMPLATE,
}